name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # OpenJDK distribution
          cache: gradle  # Cache Gradle dependencies

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build  # Compiles, tests, and generates debug/release APKs

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: app/build/outputs/apk/**/*.apk  # Uploads the compiled APKs for download
